id: ashrae-energy-prediction
name: Ashrae Energy Prediction
competition_type: simple  # Unsure of how this is chosen
awards_medals: true  # Not sure about this
prizes:
  - position: 1
    value: 10000
  - position: 2
    value: 7000
  - position: 3
    value: 5000
  - position: 4
    value: 2000
  - position: 5
    value: 1000
description: timeseriesgym/competitions/ashrae-energy-prediction/description.md

dataset:
  answers: ashrae-energy-prediction/prepared/private/test.csv
  sample_submission: ashrae-energy-prediction/prepared/public/sample_submission.csv

grader:
  name: root-mean-squared-logarithmic-error
  grade_fn: timeseriesgym.competitions.ashrae-energy-prediction.grade:grade

preparer: timeseriesgym.competitions.ashrae-energy-prediction.prepare:prepare
