id: hms-harmful-brain-activity-classification
name: HMS - Harmful Brain Activity Classification
competition_type: code  # [TODO]: change it to our competition type
awards_medals: true
prizes:
  - position: 1
    value: 20000
  - position: 2
    value: 12000
  - position: 3
    value: 7000
  - position: 4
    value: 6000
  - position: 5
    value: 5000
description: timeseriesgym/competitions/hms-harmful-brain-activity-classification/description.md

dataset:
  answers: hms-harmful-brain-activity-classification/prepared/private/test.csv
  gold_submission: hms-harmful-brain-activity-classification/prepared/private/gold_submission.csv
  sample_submission: hms-harmful-brain-activity-classification/prepared/public/sample_submission.csv

grader:
  name: kl-divergence
  grade_fn: timeseriesgym.competitions.hms-harmful-brain-activity-classification.grade:grade

preparer: timeseriesgym.competitions.hms-harmful-brain-activity-classification.prepare:prepare
