id: optiver-realized-volatility-prediction-hyperparameter-search
name: Optiver Realized Volatility Prediction with Hyperparameter Search
competition_type: simple
awards_medals: true
prizes:
  - position: 1
    value: 25000
  - position: 2
    value: 20000
  - position: 3
    value: 15000
  - position: 4
    value: 10000
  - position: 5
    value: 5000

description: timeseriesgym/competitions/optiver-realized-volatility-prediction-hyperparameter-search/description.md

parent_id: optiver-realized-volatility-prediction

dataset:
  answers: optiver-realized-volatility-prediction-hyperparameter-search/prepared/private/test.csv
  sample_submission: optiver-realized-volatility-prediction-hyperparameter-search/prepared/public/sample_submission.csv

grader:
  name: custom-hyperparameter-search-grading
  grade_fn: timeseriesgym.competitions.optiver-realized-volatility-prediction-hyperparameter-search.grade:grade_hyperparameter_search

hyperparameter_search_config:
  baseline_submission_name: baseline_submission.csv
  improved_submission_name: submission.csv
  baseline_model_name: baseline_model.pkl
  improved_model_name: model.pkl
